### ISSUE TITLE
transparent trakt call

### ISSUE THREAD

**Issue by GreenAir** [Razzeee/script.module.trakt#4]
I just opened an issue on fuzeman/trakt.py but just realised I need it in your kodi module ;-) 
  
could you add a possibility for transparent trakt calls for functions that are not supported?
e.g. collection=Trakt['shows/'+showID+'/progress/collection']

maybe it is already possible but your interface-machine is too complicated for me to understand properly! :-/

**Comment by Razzeee** [comment]
Well this just pulls in the package done by fuzeman, so he needs to do it

**Comment by Razzeee** [comment]
Btw I think it's possible just check script.trakt for an example
